### ISSUE TITLE
계산노드 배기 발열 개선

### ISSUE THREAD

**Issue by jhgoh** [cpnr/computing#37]
각 계산노드들의 발열이 평균 50도에서 60도 정도로 약간 높은 것으로 보임.
단, ho-oh노드의 경우만 온도가 낮은 편인데, full-load로 실행중에도 온도가 높지 않은 편임.

아마 랙에 각 서버가 설치될 때 상하로 공간이 떨어져 있는 경우 온도가 낮은 것 같음.
업체 방문 기회가 있을 때 각 서버들마다 1U 정도씩 공간을 두도록 요청하면 좋겠음.

lapras의 경우는 GPU full load시 온도가 80도 수준으로 높이 올라가는 것으로 보이는데,
흡, 배기 팬의 설정을 조절할 수 있을 것으로 기대됨. 단, 바이오스 화면에서 조정해야 하기 때문에 shutdown 필요함.

**Comment by JunwonTomOh** [comment]
lapras 냉각 관련
* 냉각 순서
물탱크 -> GPU -> 480mm 라디에이터 -> cpu -> 480mm 라디에이터 -> 물통

*BIOS관련
팬 설정 뿐만 아니라 워터 펌프도 pwm 4핀으로 조절되는 것으로 보임. 
BIOS에서 함께 조절하여 유속을 올려 냉각에 도움을 줄 수 있음.

* 흡/배기
흡기팬: 8개 / 배기팬: 2개 
-> 현저히 낮은 배기팬 숫자로 인해 본체 내부에 열기가 남아있음
-> 본체 상단부에 추가 시스템 쿨러 설치 가능

**Comment by JunwonTomOh** [comment]
GPU온도는 이해할 수 있는 범위인데 CPU온도가 좀 많이 높네요.
![image](https://github.com/cpnr/computing/assets/126056589/02716208-12f0-45fb-880d-c844a713da74)

**Comment by jhgoh** [comment]
> <img alt="image" width="472" src="https://private-user-images.githubusercontent.com/4388926/346443453-d6b7e1dc-0449-488d-9d35-3748e236bc52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MTg0NDMsIm5iZiI6MTcyMDQxODE0MywicGF0aCI6Ii80Mzg4OTI2LzM0NjQ0MzQ1My1kNmI3ZTFkYy0wNDQ5LTQ4OGQtOWQzNS0zNzQ4ZTIzNmJjNTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDhUMDU1NTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmRlNmNkYWFlZTMzYzliNGM5ZWUxMTFmODQ5NmM2YTgxOGY5ZGJiMGQwNzdiMTY4NWE5YWFkYzk5ZjUyMWQ1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2s9gtPgOhQCUnQLvn930554gRFDg9yd5JljpIg6yP8M">

#48 의 하부 issue로 분류. 이 issue는 닫습니다.
