### ISSUE TITLE
mattermost webhook 동작 문제

### ISSUE THREAD

**Issue by jhgoh** [cpnr/computing#42]
mattermost webhook이 동작하지 않음.

<img width="1017" alt="image" src="https://github.com/cpnr/computing/assets/4388926/fb8a5425-103f-4506-821b-72479d2e70f5">

webhook URL의 secret key를 업데이트 해야 할 것으로 보임.

**Comment by slowmoyang** [comment]
저도 같은 문제를 겪고 있습니다. 뭐가 문제인지 확인은 해보지는 않았지만... 해결하면 여기에 공유하겠습니다

**Comment by slowmoyang** [comment]
네 `mattermost/action-mattermost-nofity` 사용합니다.

https://github.com/slowmoyang/khu-saja-dataset/blob/tttt-14TeV/.github/workflows/action-mattermost-notify.yaml

![image](https://github.com/cpnr/computing/assets/20718100/9a93451f-4801-40f4-8fa0-121f0a28d01b)

**Comment by jhgoh** [comment]
github과 action-mattermost-notify가 일부 업데이트 되면서 생긴 문제로 추정함.
- 이전 구현에서는 json형식으로 파일을 내보내기 한 다음, mattermost-notify가 해당 파일을 읽어 처리하게 되어 있었음
- 파일을 통해서 각 스텝간 정보를 전달하는 대신 $GITHUB_ENV나 $GITHUB_OUTPUT을 이용하는 방식을 사용해야 하는 것으로 보임.
- mattermost-nofity에서 PAYLOAD_FILE이 deprecate되었고,PAYLOAD에 json 내용을 통째로 넘기거나, TEXT에 텍스트 내용만 넘기는 방식으로 구현 변경 된 것으로 보임.

**Comment by jhgoh** [comment]
<img width="547" alt="image" src="https://github.com/cpnr/computing/assets/4388926/647c0b34-ee44-4909-b5a3-5196b2f7d1c7">

**Comment by jhgoh** [comment]
일단 문제 해결되었으므로 이 issue는 닫습니다.
하는 김에 본문 내용을 추가하거나 하는 방식으로 yaml파일을 업데이트 해 둘 생각입니다.

**Comment by jhgoh** [comment]
testing..

**Comment by jhgoh** [comment]
testing2
