### ISSUE TITLE
hep 접근 불가

### ISSUE THREAD

**Issue by jhgoh** [cpnr/computing#63]
hep 서버 접근 불가 상황

**Comment by JunwonTomOh** [comment]
![KakaoTalk_Photo_2024-12-06-15-39-15](https://github.com/user-attachments/assets/857da54e-e70e-463f-a3d9-c0371bf0cfbb)

**Comment by JunwonTomOh** [comment]
![F9B5CDB6-3904-480E-89CC-E66794B5EE01_1_105_c](https://github.com/user-attachments/assets/fbf0c073-0bc8-4a36-b373-e55e0d0dfb22)

**Comment by jhgoh** [comment]
특별한 조치 없이 해결됨. 
문제 상황중에는 랜포트의 링크 LED가 들어오지 않은 것으로 보아 푸른솔 스위치 전원 문제가 있었던 것으로 추정.
